# Generated by Django 5.2.8 on 2025-11-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='liked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='telegram_id',
            field=models.BigIntegerField(),
        ),
    ]
