# Generated by Django 5.2.8 on 2025-12-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_receipt_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending_payment', 'Esperando Pago'), ('payment_submitted', 'Pago Enviado'), ('payment_approved', 'Pago Aprobado'), ('payment_rejected', 'Pago Rechazado')], default='pending_payment', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
