# Generated by Django 5.2.8 on 2025-12-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_order_payment_data_order_payment_receipt_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
