# Generated by Django 5.2.8 on 2025-11-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_userpreference_liked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('learned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
