# Generated by Django 5.2.8 on 2026-01-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_order_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('PICKUP', 'Pick Up'), ('DELIVERY', 'Delivery')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('HERE', 'Eat Here'), ('TOGO', 'To Go')], default='HERE', max_length=20),
        ),
    ]
