# Generated by Django 5.2.8 on 2026-01-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_order_delivery_mode_order_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('state', models.CharField(default='IDLE', max_length=50)),
                ('current_product_id', models.IntegerField(blank=True, null=True)),
                ('temp_data', models.JSONField(blank=True, default=dict)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
