# Generated by Django 5.2.8 on 2025-11-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('listo', 'Listo')], default='pendiente', max_length=50),
        ),
    ]
