# Generated by Django 5.2.8 on 2026-01-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_telegramsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='PaymentHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashes', to='bot.order')),
            ],
        ),
    ]
