# Generated by Django 5.2.8 on 2026-01-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_order_payment_hash_paymenthash'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('puntos', models.IntegerField(default=0)),
                ('nivel', models.CharField(default='Bronce', max_length=50)),
                ('total_gastado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
