# Generated by Django 5.2.8 on 2026-01-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='sentimiento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
