# Generated by Django 5.2.8 on 2026-01-11 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_order_currency_order_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Monto a descontar en $', max_digits=10)),
                ('points_cost', models.IntegerField(default=0, help_text='Puntos necesarios para canjear (0 para cupón gratis)')),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RedeemedCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('date_used', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.coupon')),
            ],
        ),
    ]
