# Generated by Django 5.2.8 on 2026-01-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_rename_active_coupon_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
