# Generated by Django 5.2.8 on 2026-01-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_order_invoice_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='redeemedcoupon',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
