# Generated by Django 5.2.8 on 2026-01-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_order_customer_name_redeemedcoupon_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('RETIRO', 'Retiro en Local'), ('DELIVERY', 'Delivery')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('AQUI', 'Comer Aquí'), ('LLEVAR', 'Para Llevar')], default='AQUI', max_length=20),
        ),
    ]
