# Generated by Django 5.2.8 on 2025-11-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('promociones', 'Promociones'), ('entradas', 'Entradas'), ('principales', 'Principales'), ('postres', 'Postres'), ('bebidas', 'Bebidas')], default='promociones', max_length=20),
        ),
    ]
