# Generated by Django 5.2.8 on 2025-11-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
