# Generated by Django 5.2.8 on 2025-12-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('promociones', 'promociones'), ('entradas', 'entradas'), ('principales', 'principales'), ('postres', 'postres'), ('bebidas', 'bebidas')], default='promociones', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('ingredientes', models.ManyToManyField(blank=True, related_name='productos', to='core.ingredient')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
