# Generated by Django 5.2.8 on 2025-12-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='disponible_como_extra',
            field=models.BooleanField(default=False),
        ),
    ]
