# Generated by Django 5.2.8 on 2026-01-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_product_cost_price_payrollpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flavor',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramo (kg)'), ('und', 'Unidad (und)'), ('l', 'Litro (l)')], default='und', max_length=5),
        ),
    ]
